
version: "3"

services:
  app:
    image: ${APP_NAME}-app:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-app
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ../:/app
      - ../../../common:/app/common
    command: bash -c "python app/main.py & python app/worker.py"
    environment:
      - C_FORCE_ROOT=true
    env_file: ${PWD}/.env
    networks:
      - celery_study_net

  redis:
    image: redis:5.0-alpine
    container_name: ${APP_NAME}-redis
    hostname: redis
    ports: 
      - 6379:6379
    restart: unless-stopped
    volumes: 
      - proj-redis:/data
    networks:
      - celery_study_net
  
  worker:
    container_name: ${APP_NAME}-worker
    build: 
      context: .
      dockerfile: Dockerfile
    command: python core/run_celery.py #celery -A app.worker.celery worker --loglevel=info
    environment:
      - C_FORCE_ROOT=true
    volumes:
      - ../:/app
      - ../../../common:/app/common
    depends_on:
      - app
      - redis
    networks:
      - celery_study_net

volumes:
  proj-redis:

networks:
  celery_study_net:
  #  external: true