
version: "3"

services:
  app:
    image: ${APP_NAME}:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}
    restart: always
    healthcheck:
     test: ["CMD-SHELL", "wget -nv -t1 --spider http://localhost:${APP_PORT}/api || exit 1"]
     interval: 30s
     timeout: 3s
     retries: 3
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ../:/app
      - ../../../core:/app/core
      - ../../../common:/app/common
      - ../../../logs:/logs
      - ../../../files:/files
    command: python main.py
    env_file: ${PWD}/.env
    networks:
      - kong

  redis:
    image: redis:5.0-alpine
    container_name: redis
    hostname: redis
    ports: 
      - 6379:6379
    restart: unless-stopped
    volumes: 
      - proj-redis:/data
    networks:
      - kong
  
  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - ../:/app
      - ../../../core:/app/core
      - ../../../common:/app/common
      - ../../../logs:/logs
      - ../../../files:/files
    depends_on:
      - app
      - redis
    networks:
      - kong

volumes:
  proj-redis:

networks:
  kong:
  #  external: true